development:
   adapter: mysql2
   encoding: utf8
   database: planbdb
   username: root
   password: waacc
   host: localhost
   port: 3306

test:
   adapter: mysql2
   encoding: utf8
   database: planbdb
   username: root
   password: waacc
   host: localhost
   port: 3306

production:
  adapter: postgresql
  encoding: unicode
  database: planbdb
  pool: 5
  username: planb
  password: waacc
