
development:
   adapter: mysql
   encoding: utf8
   database: si_blog_db
   username: planb
   password: waacc
   socket: /tmp/mysql.sock

test:
   adapter: mysql
   encoding: utf8
   database: si_blog_db
   username: planb
   password: waacc
   socket: /tmp/mysql.sock

production:
  adapter: postgresql
  encoding: unicode
  database: si_blog_db
  pool: 5 
  username: planb
  password: waacc 
